### PR TITLE
Additional features - 2

### LINKED ISSUE #13: time parsing error
When an event is created through webclient, finish time parsed unexpectedly, example can be seen given below. 
- **Create an event which has finish time of 22-02-2019 (-selected- )**

Screenshot 2020-02-22 at 15 08 43

- **However when event is created shown and written date is different than what is typed in create event modal. It can be observed on webclient and also in event yaml file** 

 
Screenshot 2020-02-22 at 15 18 43

- **Event file dates on host**

Screenshot 2020-02-22 at 15 24 31

### PR DESCRIPTION
**Pull request by gianmarcomennecozzi**

### CODE REVIEW

**Comment by mrtrkmn** [comment]
Great !  Well done !! 👏🏻

However, there is still something to develop apparently, the finish date of the events does not seem correct, but I think, it is related to Haaukins, instead webclient.  Furthermore, the spinning icon when event started to create, prevents any other functionality, it is much reasonable to make it in background as progress  or spinning bar.

**Comment by mrtrkmn** [comment]
I think, there is no problem in Haaukins side for finish time, when I supplied finish time by command line it parses and returns correct date however when I create event through web client by selecting finish time, it does not work. Needs to be fixed, before merging.

**Comment by gianmarcomennecozzi** [comment]
Need to test if the make request event message is sent to Slack.

File: client/src/Pages/Home.vue [hunk 1]
```diff
@@ -25,6 +25,15 @@
                     <span aria-hidden="true">&times;</span>
                 </button>
             </div>
+            <div v-if="createEventProgress" class="alert alert-warning alert-dismissible">
+                <div class="d-inline mr-2">
+                    <img class="loading-logo" src="../assets/bluelogo.png" width="50" height="50">
```
Comment (mrtrkmn) [inline client/src/Pages/Home.vue:30]: I think, the functionality that we have talked about did not implemented in this changes, it was taking loading in background to do not prevent any other functionality when create event is loading. We can discuss it.

File: client/src/Pages/Home.vue [hunk 2]
```diff
@@ -126,8 +144,8 @@
                 const that = this
 
                 if (this.memory <= 85){
```
Comment (mrtrkmn) [inline client/src/Pages/Home.vue]: We can also increase the check up to 95.

File: client/src/components/EventModal.vue [hunk 3]
```diff
@@ -203,14 +240,57 @@
...
+                        "User: *" + localStorage.getItem("user-email") + "*\n" +
+                        "Event Tag: *" + this.eventTag + "*\n" +
+                        "Start Time: *" + this.get_date(this.eventStartTime) + "*\n" +
+                        "Finish Time: *" + this.get_date(this.eventFinishTime) + "*\n" +
+                        "Availability: *" + this.eventAvailability + "*\n" +
+                        "Capacity: *" + this.eventCapacity + "*\n" +
+                        "Frontend: *" + this.selectedFrontends + "*\n" +
+                        "Challenges: *" + this.selectedChallenges + "*";
+
+                window.console.log(process.env.SLACK_API_KEY);
```
Comment (mrtrkmn) [inline client/src/components/EventModal.vue]: Could be nice if we remove it :) and change the name of  environment variable (SLACK_API_KEY) to something else, since it is leaked to github already.

File: proto/daemon.proto [hunk 4]
```diff
@@ -62,9 +65,15 @@ message CreateEventRequest {
     repeated string exercises = 4;
     int32 available = 5;
     int32 capacity = 6;
-    string finishTime = 7;
+    string startTime = 7;
+    string finishTime = 8;
+    bool isBooked = 9;
```
Comment (mrtrkmn) [inline proto/daemon.proto]: removed, requires update.

File: client/src/Pages/Home.vue [hunk 5]
```diff
@@ -183,13 +200,20 @@
                     }
                 });
             },
+            bookingValue: function (value){
```
Comment (mrtrkmn) [inline client/src/Pages/Home.vue:212]: I could not entirely understand this functionality, I think, I will consult you about it, tomorrow.

**Review by mrtrkmn — COMMENTED** [review]
Cool ! Web client is getting much functionality step by step :) .   As for as I understand from the review, 
- Making request functionality added 
- Desc of fields added on create event modal 
I have made some comments, which we can discuss them soon. Then, we can merge.

File: client/src/Pages/Home.vue (hunk 1 above)
Comment (gianmarcomennecozzi) [reply client/src/Pages/Home.vue:30]: the loading screen that didn't allow you to use any other functionality has been removed in this pull request. I have added an alert that show you when haaukins is creatian an event.

Comment (mrtrkmn) [reply client/src/Pages/Home.vue:30]: owh ok, then. Sorry I am not well at this syntax. :)

**Comment by gianmarcomennecozzi** [comment]
Remember to check if it is able to make a request to slack api

File: client/src/components/EventModal.vue (hunk 3 above)
Comment (mrtrkmn) [reply client/src/components/EventModal.vue]: SLACK_API_KEY does not work.

Comment (mrtrkmn) [reply client/src/components/EventModal.vue]: @gianmarcomennecozzi This library could be useful to use to get SLACK running, https://github.com/slackapi/node-slack-sdk

**Review by mrtrkmn — CHANGES_REQUESTED** [review]
Perfect ! 

The only thing which is not working is make request functionality over slack. The provided library in comments might work, otherwise an email service should be introduced.

**Review by gianmarcomennecozzi — COMMENTED** [review]
Well Done!
